In [2]:
#Lists
myList=[0,23,76.86]
myList

[0, 23, 76.86]

In [3]:
type(myList)

list

In [6]:
l1=[90,'Madhav',"Krishna",84.3,False]
l1

[90, 'Madhav', 'Krishna', 84.3, False]

In [8]:
type(l1)

list

In [10]:
l2=[myList,l1]
l2

[[0, 23, 76.86], [90, 'Madhav', 'Krishna', 84.3, False]]

---

In [12]:
#Range
range(10)

range(0, 10)

In [14]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [16]:
a=list(range(10,20))
a

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [17]:
a=list(range(10,20,2))
a

[10, 12, 14, 16, 18]

---

---

In [18]:
#Using [] brackets
a[0]
a[4]

18

In [20]:
len(a)

5

In [21]:
print(a[4]," ",a[-1]) #Negative index

18   18


In [25]:
#A test code to swap value of two lists
a=list(range(10,20,2))
b=list(range(11,20,2))
#print(len(a)," ",len(b))
print("Before swap- a= ",a," and b= ",b)
for i in range(5):
    a[i]=a[i]+b[i]
    b[i]=a[i]-b[i]
    a[i]-=b[i]
print("After swap- a= ",a," and b= ",b)

Before swap- a=  [10, 12, 14, 16, 18]  and b=  [11, 13, 15, 17, 19]
After swap- a=  [11, 13, 15, 17, 19]  and b=  [10, 12, 14, 16, 18]


---

---

In [35]:
#Slicing
letters=['a','b','c','d','e','f','g','h','i','j','k','l','m']
l1=letters[0:12]   #end index isn't inclusive
l2=letters[0:12:3] #slicing with step
l3=letters[::-1]   #negative step- genrates list in reverse order
print(l1)
print(l2)
print(l3)

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']
['a', 'd', 'g', 'j']
['m', 'l', 'k', 'j', 'i', 'h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']


---

---

In [39]:
#Tuples
tup1=(10,20,30)
print(tup1[0])
#tup[0]=5 generates error since tuples are immutable

10


---

---

In [42]:
#Functions
m1=max(tup1)
m2=min(tup1)
print(m1," ",m2)

30   10


---

---

In [44]:
#Packages
import scrapy

ModuleNotFoundError: No module named 'scrapy'

In [47]:
import numpy
#numpy.

---

---

In [51]:
#Arrays
import numpy as np
arr=np.array([2,23,56])
arr

array([ 2, 23, 56])

In [53]:
arr.mean()

27.0

In [62]:
#Slicing arrays
arr2=np.array([1,2,3,4,5,6])
arr2[1:3]

array([2, 3])

In [64]:
arr3=arr2[1:3]
arr4=arr2.copy()
arr3[:]=7
print(arr3)
print(arr2) #change in view is reflected back
print(arr4) #change isn't reflected in copy, unlike it's in the original

[7 7]
[1 7 7 4 5 6]
[1 2 3 4 5 6]
